### ISSUE TITLE
HASURA_GRAPHQL_DATABASE_URL should be in secrets instead of environment

### ISSUE THREAD

**Issue by ivawzh** [cheslip/aws-cdk-hasura#1]
Just guess you would want to move `HASURA_GRAPHQL_DATABASE_URL` to `secrets`, as it contains your db password and environment is visible to any AWS logged in users.

https://github.com/cheslip/aws-cdk-hasura/blob/0a813ca617b0dc063cffc5fe348f81d4c1300dfb/src/index.ts#L124-L126

**Comment by cheslip** [comment]
thanks for reporting
